[package]
name = "tssh"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
p256 = { version = "0.13", features = ["ecdh"] }
sha2 = { version = "0.10", features = ["oid"] }
rsa = "0.9.8"
rand_core = "0.6"