[package]
name = "tssh"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8.5"
p256 = { version = "0.13", features = ["ecdh"] }
sha2 = { version = "0.10", features = ["oid"] }
aes = "0.8.4"
hmac = "0.12.1"
rsa = "0.9.8"
rand_core = "0.6"
rpassword = "7.4.0"